### PR TITLE
contracts: Fix test gas issues

### LINKED ISSUE #765: Errors when running test
Easy to repro:

```
yarn test
```
after starting a local hardhat node

Fails on getting to test:dev-frontend with the following error:

```ProviderError: Nonce too high. Expected nonce to be 18 but got 19. Note that transactions can't be queued when automining.```

### PR DESCRIPTION
**Pull request by bingen**
Fixes #765 
Replaces #774

### CODE REVIEW

**Review by RickGriff — APPROVED** [review]
LGTM!

File: packages/contracts/utils/testHelpers.js [hunk 1]
```diff
@@ -940,16 +940,20 @@ class TestHelper {
 
   // --- Redemption functions ---
 
-  static async redeemCollateral(redeemer, contracts, LUSDAmount, maxFee = this._100pct) {
+  static async redeemCollateral(redeemer, contracts, LUSDAmount, gasPrice = 0, maxFee = this._100pct) {
```
Comment (appbak3r) [inline packages/contracts/utils/testHelpers.js:943]: Changing arguments position could result in unexpected behavior, which actually happened and tests are failing now

@edmulraney  @RickGriff
