### PR TITLE
Fix total collateral in subgraph

### LINKED ISSUE #591: Incorrect total collateral in subgraph after redistribution
The 0.5% of a redistributed Trove's collateral that's paid out to the liquidator as gas compensation isn't subtracted from total collateral.

### PR DESCRIPTION
**Pull request by danielattilasimon**
Total collateral was incorrect after a redistribution, because we weren't subtracting the 0.5% collateral paid out as gas compensation.
    
Fixes #591.

### CODE REVIEW

File: packages/subgraph/src/entities/SystemState.ts [hunk 1]
```diff
@@ -135,15 +145,22 @@ export function updateSystemStateByTroveChange(troveChange: TroveChange): void {
...
+
+    systemState.totalCollateral = systemState.totalCollateral.minus(collateralGasCompensation);
+
     if (!isRecoveryModeLiquidation(operation) || troveChange.collateralRatioBefore > DECIMAL_ONE) {
       tryToOffsetWithTokensFromStabilityPool(
         systemState,
-        -troveChange.collateralChange,
-        -troveChange.debtChange
+        collateral.minus(collateralGasCompensation),
+        debt
```
Comment (bingen) [inline packages/subgraph/src/entities/SystemState.ts:163]: I don’t get how this is equivalent. Letting aside the gas compensation, it seems that now we are using “before” values, instead of “change” values. What am I missing?

Comment (danielattilasimon) [reply packages/subgraph/src/entities/SystemState.ts:163]: I originally used the change values, because back then there used to be partial liquidation, which didn't completely erase the Trove. With those out of the picture, collateralChange and debtChange are always equal to -collateral and -debt, so it's simpler to just use collateral and debt.

Comment (bingen) [reply packages/subgraph/src/entities/SystemState.ts:163]: Makes sense, thanks!

**Review by bingen — APPROVED** [review]
